/////////
// LOGIN ACTIONS
///////
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/////////
// LOGOUT ACTIONS
///////
export const LOGOUT = 'LOGOUT';
/////////
// SIGNUP ACTIONS
///////
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
/////////
// ALERT ACTIONS
///////
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
/////////
// RESOURCES ACTIONS
///////
export const GET_RESOURCES_START = 'GET_RESOURCES_START';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';
export const CREATE_RESOURCE_START = 'CREATE_RESOURCE_START';
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS';
export const CREATE_RESOURCE_FAIL = 'CREATE_RESOURCE_FAIL';
export const INCREMENT_DOWNLOAD = 'INCREMENT_DOWNLOAD';
/////////
// STUDENT ACTIONS
///////
export const GET_STUDENT_START = 'GET_STUDENT_START';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';
export const AUTH_STUDENT_IMAGE_UPDATE = 'AUTH_STUDENT_IMAGE_UPDATE';
export const AUTH_STUDENT_DATA_UPDATE = 'AUTH_STUDENT_DATA_UPDATE';
/////////
// Notice ACTIONS
///////
export const GET_NOTICE_START = 'GET_NOTICE_START';
export const GET_NOTICE_SUCCESS = 'GET_NOTICE_SUCCESS';
export const GET_NOTICE_FAIL = 'GET_NOTICE_FAIL';

export const POST_NOTICE_START = 'POST_NOTICE_START';
export const POST_NOTICE_SUCCESS = 'POST_NOTICE_SUCCESS';
export const POST_NOTICE_FAIL = 'POST_NOTICE_FAIL';
